import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";
import { CommandBox } from "@/components/navigation/CommandBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Connec",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<NextTopLoader
						color="#71717a"
						initialPosition={0.08}
						crawlSpeed={200}
						height={3}
						crawl={true}
						showSpinner={false}
						easing="ease"
						speed={200}
					/>

					<div className="w-full h-full flex justify-center">{children}</div>
					<CommandBox />
				</body>
			</html>
		</ClerkProvider>
	);
}
