import type { Metadata } from "next";

import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";
import Banner from "@/components/content/Banner";

export const metadata: Metadata = {
	title: "Connec",
	description: "Generated by create next app",
};

export default function ContentLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="flex flex-col w-full">
			<Banner />
			<Navbar />
			<div className="mt-16">{children}</div>
			{/* <Footer /> */}
		</div>
	);
}
